
create table if not exists public.client_access_links (
  id bigint generated by default as identity primary key,
  token text not null unique,
  client_name text,
  client_email text not null,
  company text,
  plan text,
  status text default 'active',
  expires_at timestamptz,
  open_count integer default 0,
  last_opened_at timestamptz,
  created_at timestamptz default now()
);

create index if not exists client_access_links_token_idx
on public.client_access_links(token);

alter table public.client_access_links enable row level security;

-- Доступ к этой таблице идет только через server-side API с service role.
-- Публичные политики не нужны.
