create table if not exists public.client_checks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  type text,
  status text default 'in_progress',
  risk_score integer,
  summary text,
  report_url text,
  created_at timestamptz default now()
);

alter table public.client_checks enable row level security;

drop policy if exists "Clients can read own checks" on public.client_checks;

create policy "Clients can read own checks"
on public.client_checks
for select
to authenticated
using (auth.uid() = user_id);

-- Для теста:
-- 1. Зарегистрируй пользователя на /account
-- 2. В Supabase открой Authentication -> Users
-- 3. Скопируй id пользователя
-- 4. Выполни insert ниже, заменив PASTE_USER_ID_HERE

-- insert into public.client_checks
-- (user_id, title, type, status, risk_score, summary, report_url)
-- values
-- ('PASTE_USER_ID_HERE', 'Проверка контрагента Northbridge Trading', 'counterparty', 'in_progress', 72, 'Проверяются бенефициары, судебная история и санкционная экспозиция.', null);
