create table if not exists public.heimdall_crm_meta (
  id bigint generated by default as identity primary key,
  lead_source text not null default 'heimdall_leads',
  lead_id text not null,
  status text not null default 'new',
  priority text not null default 'normal',
  amount numeric,
  responsible text,
  next_action text,
  next_contact_at timestamptz,
  internal_comment text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (lead_source, lead_id)
);

create index if not exists heimdall_crm_meta_lead_idx
on public.heimdall_crm_meta(lead_source, lead_id);

create index if not exists heimdall_crm_meta_status_idx
on public.heimdall_crm_meta(status);

create index if not exists heimdall_crm_meta_next_contact_idx
on public.heimdall_crm_meta(next_contact_at);

alter table public.heimdall_crm_meta enable row level security;

-- Таблица используется только server-side API с Supabase service role.
-- Публичные политики не нужны.
