import Head from 'next/head'
import Link from 'next/link'
import HeimdallLogo from '@/components/HeimdallLogo'
import { ArrowRight, AlertTriangle, CheckCircle2, ShieldCheck, Eye, Network, FileSearch } from 'lucide-react'

const findings = [["Непрозрачная структура", "Выявлены промежуточные юридические лица в другой юрисдикции."], ["Связанный директор", "Один из директоров связан с компанией, фигурирующей в судебном споре."], ["Репутационный сигнал", "В открытых источниках выявлены негативные публикации."], ["Документы требуют проверки", "Пакет документов неполный и содержит расхождения."]]
const sections = ["Структура владения", "Санкционные сигналы", "Судебная история", "Репутационный фон"]

export default function DemoReportPage() {
  return (
    <>
      <Head><title>Демо-отчёт HEIMDALL — HEIMDALL</title><meta name="description" content="Демонстрационный формат отчёта: индекс риска, краткое заключение, выявленные факты и рекомендация." /></Head>
      <main className="min-h-screen overflow-hidden bg-[#050816] text-white">
        <div className="fixed inset-0 pointer-events-none"><div className="absolute inset-0 bg-[radial-gradient(circle_at_16%_12%,rgba(37,99,235,0.26),transparent_32%),radial-gradient(circle_at_84%_18%,rgba(14,165,233,0.14),transparent_30%),linear-gradient(135deg,#050816_0%,#08111f_48%,#050816_100%)]" /><div className="absolute inset-0 opacity-[0.06] [background-image:linear-gradient(rgba(255,255,255,0.12)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.12)_1px,transparent_1px)] [background-size:48px_48px]" /></div>
        <header className="relative z-10 border-b border-white/10 bg-[#050816]/70 backdrop-blur-2xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5"><HeimdallLogo /><div className="flex gap-3"><Link href="/demo-report-en" className="rounded-full border border-white/10 bg-white/5 px-4 py-2 text-sm">EN</Link><Link href="/#lead" className="rounded-full bg-sky-500 px-5 py-2.5 text-sm font-semibold">Запросить проверку</Link></div></div></header>
        <section className="relative z-10 mx-auto max-w-7xl px-5 py-24"><div className="grid gap-12 lg:grid-cols-[0.95fr_1.05fr] lg:items-center"><div><div className="inline-flex items-center gap-3 rounded-full border border-sky-300/20 bg-sky-300/10 px-5 py-2 text-sm uppercase tracking-[0.24em] text-sky-200"><Eye className="h-4 w-4" /> Demo Intelligence Report</div><h1 className="mt-10 text-5xl font-semibold leading-[0.95] tracking-[-0.06em] md:text-8xl">Как выглядит управленческий отчёт HEIMDALL</h1><p className="mt-10 max-w-3xl text-xl leading-9 text-white/64">Демонстрационный формат отчёта: индекс риска, краткое заключение, выявленные факты и рекомендация.</p></div><div className="rounded-[42px] border border-sky-300/20 bg-white/[0.045] p-7 backdrop-blur-2xl"><div className="rounded-[34px] border border-white/10 bg-[#07101f]/90 p-7"><div className="flex items-center justify-between"><div><div className="text-xs uppercase tracking-[0.25em] text-sky-300/70">Индекс риска</div><div className="mt-3 text-7xl font-semibold tracking-[-0.08em] text-sky-100">72</div></div><div className="flex h-32 w-32 items-center justify-center rounded-full border border-amber-300/30 bg-amber-300/10 text-amber-200"><AlertTriangle className="h-12 w-12" /></div></div><div className="mt-8 h-3 overflow-hidden rounded-full bg-white/10"><div className="h-full w-[72%] rounded-full bg-gradient-to-r from-sky-400 via-amber-300 to-rose-400" /></div></div></div></div></section>
        <section className="relative z-10 mx-auto max-w-7xl px-5 pb-24"><div className="grid gap-5 lg:grid-cols-[0.9fr_1.1fr]"><div className="rounded-[34px] border border-white/10 bg-white/[0.045] p-8 backdrop-blur-2xl"><div className="text-sm uppercase tracking-[0.25em] text-sky-300/80">Краткое заключение</div><p className="mt-6 text-xl leading-9 text-white/70">Объект проверки имеет повышенный риск из-за репутационных сигналов, непрозрачной структуры владения и связей с проблемными контрагентами.</p></div><div className="rounded-[34px] border border-amber-300/20 bg-amber-300/10 p-8 backdrop-blur-2xl"><div className="text-sm uppercase tracking-[0.25em] text-amber-200/80">Рекомендация</div><p className="mt-6 text-xl leading-9 text-white/72">Не продолжать процесс без дополнительных документов, подтверждения бенефициаров и расширенной проверки связанных лиц.</p></div></div></section>
        <section className="relative z-10 mx-auto max-w-7xl px-5 pb-24"><div className="grid gap-5 md:grid-cols-4">{sections.map((s,i)=><div key={s} className="rounded-[30px] border border-white/10 bg-white/[0.045] p-6 backdrop-blur-2xl"><div className="mb-6 flex h-12 w-12 items-center justify-center rounded-2xl border border-sky-300/20 bg-sky-300/10 text-sky-200">{i===0?<Network className="h-5 w-5" />:i===1?<ShieldCheck className="h-5 w-5" />:i===2?<FileSearch className="h-5 w-5" />:<Eye className="h-5 w-5" />}</div><h2 className="text-xl font-semibold">{s}</h2><div className="mt-5 h-2 rounded-full bg-white/10"><div className="h-full rounded-full bg-sky-400" style={{width:`${44+i*13}%`}} /></div></div>)}</div></section>
        <section className="relative z-10 mx-auto max-w-7xl px-5 pb-32"><div className="rounded-[42px] border border-white/10 bg-white/[0.045] p-8 backdrop-blur-2xl md:p-12"><div className="mb-10 text-sm uppercase tracking-[0.25em] text-sky-300/80">Findings</div><div className="grid gap-5 md:grid-cols-2">{findings.map(([a,b])=><div key={a} className="rounded-3xl border border-white/10 bg-black/25 p-6"><CheckCircle2 className="mb-5 h-5 w-5 text-sky-300" /><h3 className="text-xl font-semibold">{a}</h3><p className="mt-3 text-sm leading-7 text-white/60">{b}</p></div>)}</div><Link href="/#lead" className="mt-10 inline-flex rounded-2xl bg-sky-500 px-7 py-4 font-semibold">Запросить проверку <ArrowRight className="ml-2 h-4 w-4" /></Link></div></section>
      </main>
    </>
  )
}
